name: Update Calendar and Daily Info

on:
  schedule:
    # 以下是一些常用的 cron 设置示例：
    - cron: '0 */1 * * *'  # 每小时运行一次
    # - cron: '0 16 * * *'   # 每天北京时间 00:00 (UTC+8)
    # - cron: '0 */6 * * *'  # 每6小时
    # - cron: '0 8,20 * * *' # 每天 8:00 和 20:00
  workflow_dispatch:      # 允许手动触发

jobs:
  update-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # 获取完整历史记录用于统计
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # 使用 Node.js 18 或更高版本
          
      - name: Install dependencies
        run: npm install cheerio
          
      - name: Generate Calendar
        run: |
          node scripts/generateCalendar.js > temp_calendar.txt
          
      - name: Generate Daily Info
        run: |
          node scripts/fetchDailyInfo.js > temp_daily.txt
          
      - name: Update README
        run: |
          # 更新日历
          CALENDAR=$(cat temp_calendar.txt)
          awk -v cal="$CALENDAR" '
          /<!-- CALENDAR_START -->/{p=1; print; print cal; next}
          /<!-- CALENDAR_END -->/{p=1}
          !p{print}
          ' README.md > README.tmp
          mv README.tmp README.md

          # 更新每日资讯
          DAILY_INFO=$(cat temp_daily.txt)
          awk -v info="$DAILY_INFO" '
          /<!-- DAILY_INFO_START -->/{p=1; print; print info; next}
          /<!-- DAILY_INFO_END -->/{p=1}
          !p{print}
          ' README.md > README.tmp
          mv README.tmp README.md
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update calendar and daily info" || exit 0
          git push 